version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "database"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
